# CI de Nível 04 - Disparo dentro do fluxo de CI de desenvolvimento

name: 'Execução Integrada'

# triggers OU gatilhos de execução
  # gatilho de eexec manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ['ubuntu-latest']

    steps:

      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronizacao de codigo (Lint / Prettier)
        run: yarn lint

  #descrição do Job
  e2e-tests:

    # maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    # passo a passo das ações do job
    steps:

      - uses: actions/checkout@v4
      
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*
      
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install
      
      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report

      